datasource:
  url: jdbc:postgresql://localhost:5432/autoshow_spring
  driver: org.postgresql.Driver
  username: postgres
  password: postgres

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  format_sql: true
  physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

liquibase:
    changelog: db/changelog/db.changelog-master.yaml
